[package]
name = "unison-fmt"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "unison-fmt"
path = "src/main.rs"

[dependencies]
wasm-bindgen = "0.2"
